### ISSUE TITLE
compilation failure in Debian testing with python 2.7

### ISSUE THREAD

**Issue by barak** [thomasdeniau/pyfauxfur#1]
Running this in Debian testing, with python 2.7, and all the packages that seem needed (see git://github.com/barak/pyfauxfur README.md for package list) running the program pops up a window, but clicking the RUN button gets a compilation error.  See below for details.  Naturally, I have no clue what is going wrong.

$ ./PyFauxFur.py
Generating texture with the following parameters :
-r -s 0.0005 -a 0.25 -b 0.0625 -d 12.0 -x 400 -y 400

/usr/bin/ld: error: linker defined: multiple definition of '_end'
/usr/bin/ld: /tmp/barak/python27_intermediate/compiler_8edef1a6dab90aee86f29d975c17f66f/home/barak/.python27_compiled/sc_93e7dadbf2988faed5adeed06249bafc1.o: previous definition here
collect2: ld returned 1 exit status
/usr/bin/ld: error: linker defined: multiple definition of '_end'
/usr/bin/ld: /tmp/barak/python27_intermediate/compiler_8edef1a6dab90aee86f29d975c17f66f/home/barak/.python27_compiled/sc_93e7dadbf2988faed5adeed06249bafc1.o: previous definition here
collect2: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/barak/src/git/pyfauxfur/Controller.py", line 18, in run
    self.texture.step()
  File "/home/barak/src/git/pyfauxfur/MorphogenesisImageData.py", line 180, in step
    type_converters=weave.converters.blitz)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/inline_tools.py", line 355, in inline
    *_kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/inline_tools.py", line 482, in compile_function
    verbose=verbose, *_kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/ext_tools.py", line 367, in compile
    verbose = verbose, **kw)
  File "/usr/lib/python2.7/dist-packages/scipy/weave/build_tools.py", line 288, in build_extension
    raise e
scipy.weave.build_tools.CompileError: error: Command "g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions /tmp/barak/python27_intermediate/compiler_8edef1a6dab90aee86f29d975c17f66f/home/barak/.python27_compiled/sc_93e7dadbf2988faed5adeed06249bafc1.o /tmp/barak/python27_intermediate/compiler_8edef1a6dab90aee86f29d975c17f66f/usr/lib/python2.7/dist-packages/scipy/weave/scxx/weave_imp.o -o /home/barak/.python27_compiled/sc_93e7dadbf2988faed5adeed06249bafc1.so" failed with exit status 1

**Comment by thomasdeniau** [comment]
Sorry, I don't have time to work on this package anymore (it was originally a test assignment and I never picked it up again afterwards), but based on the stack trace you provide, it seems to be an issue deep inside scipy, not an issue in my code.

You should probably ask the scipy maintainers if they know about this problem.

**Comment by thomasdeniau** [comment]
You can add a "verbose" parameter to weave.inline (see http://docs.scipy.org/doc/scipy/reference/generated/scipy.weave.inline.html) to add more logs of the compilation process, look at the generated C file, and eventually know why the "end" symbol is defined twice.
